
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Button btnDiv;
	private global::Gtk.Entry Numero1;
	private global::Gtk.Entry Numero2;
	private global::Gtk.Entry Resultado;
	private global::Gtk.Label lblNum2;
	private global::Gtk.Label lblResultado;
	private global::Gtk.Label lblNum1;
	private global::Gtk.Button btnRes;
	private global::Gtk.Button btnSum1;
	private global::Gtk.Button btnMul;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnDiv = new global::Gtk.Button ();
		this.btnDiv.CanFocus = true;
		this.btnDiv.Name = "btnDiv";
		this.btnDiv.UseUnderline = true;
		this.btnDiv.Label = global::Mono.Unix.Catalog.GetString ("dividir");
		this.fixed1.Add (this.btnDiv);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnDiv]));
		w1.X = 300;
		w1.Y = 218;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Numero1 = new global::Gtk.Entry ();
		this.Numero1.CanFocus = true;
		this.Numero1.Name = "Numero1";
		this.Numero1.IsEditable = true;
		this.Numero1.InvisibleChar = '●';
		this.fixed1.Add (this.Numero1);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Numero1]));
		w2.X = 205;
		w2.Y = 23;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Numero2 = new global::Gtk.Entry ();
		this.Numero2.CanFocus = true;
		this.Numero2.Name = "Numero2";
		this.Numero2.IsEditable = true;
		this.Numero2.InvisibleChar = '●';
		this.fixed1.Add (this.Numero2);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Numero2]));
		w3.X = 206;
		w3.Y = 80;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.Resultado = new global::Gtk.Entry ();
		this.Resultado.CanFocus = true;
		this.Resultado.Name = "Resultado";
		this.Resultado.IsEditable = true;
		this.Resultado.InvisibleChar = '●';
		this.fixed1.Add (this.Resultado);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.Resultado]));
		w4.X = 206;
		w4.Y = 136;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblNum2 = new global::Gtk.Label ();
		this.lblNum2.Name = "lblNum2";
		this.lblNum2.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero 2");
		this.fixed1.Add (this.lblNum2);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblNum2]));
		w5.X = 69;
		w5.Y = 81;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblResultado = new global::Gtk.Label ();
		this.lblResultado.Name = "lblResultado";
		this.lblResultado.LabelProp = global::Mono.Unix.Catalog.GetString ("Resultado");
		this.fixed1.Add (this.lblResultado);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblResultado]));
		w6.X = 70;
		w6.Y = 136;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblNum1 = new global::Gtk.Label ();
		this.lblNum1.Name = "lblNum1";
		this.lblNum1.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero 1");
		this.fixed1.Add (this.lblNum1);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblNum1]));
		w7.X = 72;
		w7.Y = 28;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnRes = new global::Gtk.Button ();
		this.btnRes.CanFocus = true;
		this.btnRes.Name = "btnRes";
		this.btnRes.UseUnderline = true;
		this.btnRes.Label = global::Mono.Unix.Catalog.GetString ("restar");
		this.fixed1.Add (this.btnRes);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnRes]));
		w8.X = 132;
		w8.Y = 215;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnSum1 = new global::Gtk.Button ();
		this.btnSum1.CanFocus = true;
		this.btnSum1.Name = "btnRes1";
		this.btnSum1.UseUnderline = true;
		this.btnSum1.Label = global::Mono.Unix.Catalog.GetString ("sumar");
		this.fixed1.Add (this.btnSum1);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnSum1]));
		w9.X = 53;
		w9.Y = 216;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnMul = new global::Gtk.Button ();
		this.btnMul.CanFocus = true;
		this.btnMul.Name = "btnMul";
		this.btnMul.UseUnderline = true;
		this.btnMul.Label = global::Mono.Unix.Catalog.GetString ("multiplicar");
		this.fixed1.Add (this.btnMul);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnMul]));
		w10.X = 205;
		w10.Y = 215;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 437;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnDiv.Clicked += new global::System.EventHandler (this.OnBtnDivClicked);
		this.btnRes.Clicked += new global::System.EventHandler (this.OnBtnResClicked);
		this.btnSum1.Clicked += new global::System.EventHandler (this.OnBtnRes1Clicked);
		this.btnMul.Clicked += new global::System.EventHandler (this.OnBtnMulClicked);
	}
}
